//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorDeSazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_Sucursales
    {
        public System.Guid IDNegocio { get; set; }
        public System.Guid IDSucursal { get; set; }
        public string NombreSucursal { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaInicioOperacion { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string Calle { get; set; }
        public string NumeroExt { get; set; }
        public string NumeroInt { get; set; }
        public string Colonia { get; set; }
        public string CP { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public bool Activo { get; set; }
        public string Ubicacion { get; set; }
    
        public virtual Adm_Negocios Adm_Negocios { get; set; }
    }
}
