//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorDeSazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adm_Negocios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adm_Negocios()
        {
            this.Adm_Sucursales = new HashSet<Adm_Sucursales>();
        }
    
        public System.Guid IDNegocio { get; set; }
        public string NombreComercial { get; set; }
        public string RazonSocial { get; set; }
        public System.DateTime FechaFundacion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaBaja { get; set; }
        public bool Activo { get; set; }
        public System.Guid AIDUsuario { get; set; }
    
        public virtual Adm_Usuarios Adm_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adm_Sucursales> Adm_Sucursales { get; set; }
    }
}
