//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministradorDeSazon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdministradorDeSazonEntities : DbContext
    {
        public AdministradorDeSazonEntities()
            : base("name=AdministradorDeSazonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adm_Negocios> Adm_Negocios { get; set; }
        public virtual DbSet<Adm_Sucursales> Adm_Sucursales { get; set; }
        public virtual DbSet<Adm_Usuarios> Adm_Usuarios { get; set; }
    }
}
